export type QuizCategory =
  | 'resumeBasics'
  | 'atsFormatting'
  | 'projectsSkills'
  | 'jobApplication'
  | 'situationalScenarios'
  | 'mixed'

export type QuizDifficulty = 'beginner' | 'intermediate' | 'advanced'

export type ResumeQuizQuestion = {
  id: number
  category: QuizCategory
  difficulty: QuizDifficulty
  question: string
  options: string[]
  correctOptionIndex: number
  explanation: string
}

export const QUIZ_CATEGORIES: Array<{ key: QuizCategory; label: string }> = [
  { key: 'resumeBasics', label: 'Resume Basics' },
  { key: 'atsFormatting', label: 'ATS & Formatting' },
  { key: 'projectsSkills', label: 'Projects & Skills' },
  { key: 'jobApplication', label: 'Job Application' },
  { key: 'situationalScenarios', label: 'Situational Scenarios' },
  { key: 'mixed', label: 'Mixed Quiz' },
]

export const QUIZ_DIFFICULTIES: Array<{ key: QuizDifficulty; label: string }> = [
  { key: 'beginner', label: 'Beginner' },
  { key: 'intermediate', label: 'Intermediate' },
  { key: 'advanced', label: 'Advanced' },
]

// Manually authored static question bank: 5 categories × 21 questions = 105 questions
// IDs: resumeBasics 1-21, atsFormatting 22-42, projectsSkills 43-63, jobApplication 64-84, situationalScenarios 85-105

export const RESUME_QUIZ_QUESTIONS: ResumeQuizQuestion[] = [
  // resumeBasics (1-21)
  {
    id: 1,
    category: 'resumeBasics',
    difficulty: 'beginner',
    question: 'What is the main purpose of a resume?',
    options: [
      'To introduce your skills, education, and work experience to potential employers.',
      'To provide a personal diary of your daily activities.',
      'To list every class you have ever taken in detail.',
      'To serve as a social media profile replacement.',
    ],
    correctOptionIndex: 0,
    explanation: 'A resume gives employers a concise overview of your qualifications to decide whether to interview you.',
  },
  {
    id: 2,
    category: 'resumeBasics',
    difficulty: 'beginner',
    question: 'Where should your contact information usually appear on a resume?',
    options: [
      'Near the top so recruiters can find it quickly.',
      'Hidden at the bottom of the last page.',
      'Only in the application form, not on the resume.',
      'In a separate document labeled "Contact Info".',
    ],
    correctOptionIndex: 0,
    explanation: 'Contact details belong near the top of the resume so hiring managers can reach you without searching.',
  },
  {
    id: 3,
    category: 'resumeBasics',
    difficulty: 'beginner',
    question: 'Which format is usually easiest for hiring managers to scan?',
    options: [
      'Clear section headings and bullet points for accomplishments.',
      'Dense paragraphs describing every duty at each job.',
      'A resume built entirely with images and graphics.',
      'Single long timeline without headings.',
    ],
    correctOptionIndex: 0,
    explanation: 'Headings and bullets help reviewers quickly scan for relevant skills and achievements.',
  },
  {
    id: 4,
    category: 'resumeBasics',
    difficulty: 'beginner',
    question: 'What tense should you use for bullets describing past roles?',
    options: [
      'Past tense for previous roles and present tense for your current role.',
      'Always future tense.',
      'Always present tense for all roles.',
      'Past continuous tense only.',
    ],
    correctOptionIndex: 0,
    explanation: 'Use past tense for past roles and present tense for your current position to be clear and consistent.',
  },
  {
    id: 5,
    category: 'resumeBasics',
    difficulty: 'intermediate',
    question: 'How should you present achievements on your resume to make them persuasive?',
    options: [
      'Use measurable results and the impact of your actions.',
      'Describe only your daily tasks without results.',
      'List responsibilities without context.',
      'Use general adjectives like "responsible for" repeatedly.',
    ],
    correctOptionIndex: 0,
    explanation: 'Quantified results and clear impact show employers the value you delivered in past roles.',
  },
  {
    id: 6,
    category: 'resumeBasics',
    difficulty: 'intermediate',
    question: 'What is a strong way to write a resume summary for job applications?',
    options: [
      'A brief statement highlighting your top strengths and how they relate to the role.',
      'A full paragraph of personal background and hobbies.',
      'A list of every software you have installed.',
      'A long narrative of your life story.',
    ],
    correctOptionIndex: 0,
    explanation: 'A concise summary should present your value proposition and match the role’s needs.',
  },
  {
    id: 7,
    category: 'resumeBasics',
    difficulty: 'intermediate',
    question: 'When deciding which past jobs to include, what is best practice?',
    options: [
      'Prioritize roles that are most relevant to the position you are applying for.',
      'Include every job you ever had regardless of relevance.',
      'Only include jobs from the last month.',
      'Exclude any roles that involved teamwork.',
    ],
    correctOptionIndex: 0,
    explanation: 'Focus the resume on experience that demonstrates fit for the target role, trimming unrelated history.',
  },
  {
    id: 8,
    category: 'resumeBasics',
    difficulty: 'intermediate',
    question: 'What should you avoid placing in your resume summary?',
    options: [
      'Irrelevant personal details such as marital status or social media hobbies.',
      'A concise list of core skills.',
      'A one-line value proposition.',
      'Role-specific achievements.',
    ],
    correctOptionIndex: 0,
    explanation: 'Personal details that do not relate to job performance should be omitted to keep focus on professional qualifications.',
  },
  {
    id: 9,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'How should you tailor a senior-level resume to highlight leadership?',
    options: [
      'Emphasize strategic outcomes, team size, and measurable business impact.',
      'Only list technical tools with no context.',
      'Avoid mentioning leadership responsibilities.',
      'Use an academic CV format regardless of industry.',
    ],
    correctOptionIndex: 0,
    explanation: 'Senior resumes should focus on strategic impact, scope, and measurable results that show leadership effectiveness.',
  },
  {
    id: 10,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'What is the best way to present a promotion at the same company?',
    options: [
      'List the company once, with separate entries for each title and dates to show progression.',
      'Hide the promotion and only list the latest title.',
      'Split the company across multiple resumes with different contact info.',
      'Remove the earlier title entirely to shorten the resume.',
    ],
    correctOptionIndex: 0,
    explanation: 'Showing each title with dates demonstrates career progression and increased responsibility.',
  },
  {
    id: 11,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'How should you address a short employment gap of six months on your resume?',
    options: [
      'Briefly explain the gap (e.g., professional training, caregiving) and highlight recent achievements.',
      'Remove all dates from your resume entirely.',
      'Provide no explanation and leave a blank section.',
      'Fabricate employment to fill the gap.',
    ],
    correctOptionIndex: 0,
    explanation: 'A concise, honest explanation combined with recent accomplishments reduces recruiter concern about gaps.',
  },
  {
    id: 12,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'Which approach improves clarity when your role had varied responsibilities?',
    options: [
      'Group achievements by theme or function and provide metrics for each.',
      'Write one long paragraph covering everything in vague terms.',
      'List responsibilities in random order without headings.',
      'Omit most responsibilities to save space.',
    ],
    correctOptionIndex: 0,
    explanation: 'Grouping by theme and providing metrics helps readers understand your strengths across varied duties.',
  },
  {
    id: 13,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'When including education on a senior resume, what is best?',
    options: [
      'Include degree, institution, and graduation year (optional) and emphasize relevant coursework or honors if directly relevant.',
      'List all courses taken in college in detail.',
      'Place education at the top regardless of experience level.',
      'Exclude degree information entirely.',
    ],
    correctOptionIndex: 0,
    explanation: 'Provide concise education details and highlight items that support the role when relevant.',
  },
  {
    id: 14,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'What is a recommended way to quantify achievements for a product manager?',
    options: [
      'State measurable outcomes such as percentage increase in engagement, revenue, or retention.',
      'List the meetings you attended each week.',
      'Describe your title without results.',
      'Include only technical metrics unrelated to product outcomes.',
    ],
    correctOptionIndex: 0,
    explanation: 'Product roles benefit from outcome metrics that demonstrate the impact of decisions and initiatives.',
  },
  {
    id: 15,
    category: 'resumeBasics',
    difficulty: 'beginner',
    question: 'If you have limited work experience, what should you include to strengthen your resume?',
    options: [
      'Relevant academic projects, internships, volunteer work, and skills with brief outcomes.',
      'Only a one-line statement saying you are new to the workforce.',
      'A long list of unrelated hobbies.',
      'No contact information to keep privacy.',
    ],
    correctOptionIndex: 0,
    explanation: 'Academic projects and internships show practical experience and can demonstrate relevant skills to employers.',
  },
  {
    id: 16,
    category: 'resumeBasics',
    difficulty: 'intermediate',
    question: 'How should you order bullets under each role to maximize impact?',
    options: [
      'Place the most important, highest-impact accomplishments first.',
      'Order bullets alphabetically by word.',
      'Put the shortest sentences first regardless of importance.',
      'Randomize order to show variety.',
    ],
    correctOptionIndex: 0,
    explanation: 'Leading with the most significant achievements makes it likely reviewers see your top contributions quickly.',
  },
  {
    id: 17,
    category: 'resumeBasics',
    difficulty: 'beginner',
    question: 'Should you include references on your resume?',
    options: [
      'No—references are provided separately when requested.',
      'Yes—list at least five references directly on the resume.',
      'Include references only if they are family members.',
      'List contact information for previous managers without permission.',
    ],
    correctOptionIndex: 0,
    explanation: 'References are typically shared upon request rather than included on the resume itself.',
  },
  {
    id: 18,
    category: 'resumeBasics',
    difficulty: 'intermediate',
    question: 'What is the role of keywords in a resume?',
    options: [
      'Keywords reflect skills and terms that match the job description and help with screening and ATS matching.',
      'Keywords are decorative words that improve aesthetics.',
      'Keywords should be hidden in images.',
      'Keywords only matter for cover letters, not resumes.',
    ],
    correctOptionIndex: 0,
    explanation: 'Using relevant keywords naturally helps both ATS and human reviewers recognize fit for the role.',
  },
  {
    id: 19,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'How can you make a resume more accessible to international recruiters?',
    options: [
      'Use clear, simple language, standard date formats, and avoid region-specific acronyms without explanation.',
      'Use local slang and idioms specific to one country.',
      'Include multiple languages in every bullet point.',
      'Use a nonstandard font that may not render internationally.',
    ],
    correctOptionIndex: 0,
    explanation: 'Clear language and universal formats reduce confusion and improve comprehension across regions.',
  },
  {
    id: 20,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'What is the recommended way to handle technical versus managerial experience on the same resume?',
    options: [
      'Create distinct sections or highlight selective bullets to show both technical contributions and leadership outcomes.',
      'Exclude managerial experience entirely to focus on technical skills.',
      'Mix everything together without structure.',
      'Use two resumes simultaneously in one file.',
    ],
    correctOptionIndex: 0,
    explanation: 'Structuring sections lets you present both technical depth and managerial impact clearly for diverse roles.',
  },
  {
    id: 21,
    category: 'resumeBasics',
    difficulty: 'advanced',
    question: 'Which practice helps reduce unconscious bias during initial resume screening?',
    options: [
      'Focus on role-relevant skills and achievements and remove unnecessary personal identifiers.',
      'Add a photo and personal details to stand out.',
      'Include birthdate and marital status for clarity.',
      'Use flashy colors to draw attention.',
    ],
    correctOptionIndex: 0,
    explanation: 'Removing personal identifiers and emphasizing objective achievements helps reduce bias in screening.',
  },

  // atsFormatting (22-42)
  {
    id: 22,
    category: 'atsFormatting',
    difficulty: 'beginner',
    question: 'Which file type is typically recommended for online job submissions to preserve formatting and text?',
    options: [
      'A text-based PDF or DOCX file.',
      'A screenshot image such as PNG or JPG.',
      'A compressed archive without preview.',
      'A PowerPoint file with animations.',
    ],
    correctOptionIndex: 0,
    explanation: 'Text-based PDFs and DOCX files preserve formatting and allow ATS to read content reliably.',
  },
  {
    id: 23,
    category: 'atsFormatting',
    difficulty: 'beginner',
    question: 'Why should you avoid placing critical text inside images on a resume?',
    options: [
      'Images are often unreadable by ATS and may not be visible to screen readers.',
      'Images always improve ATS accuracy.',
      'Images reduce file size substantially.',
      'Images are required for ATS parsing in most systems.',
    ],
    correctOptionIndex: 0,
    explanation: 'Important content in images cannot be parsed by ATS and can harm accessibility for assistive technologies.',
  },
  {
    id: 24,
    category: 'atsFormatting',
    difficulty: 'beginner',
    question: 'Which section header is standard and helps ATS identify your employment history?',
    options: [
      'Experience',
      'My Story',
      'Random Notes',
      'Personal Timeline',
    ],
    correctOptionIndex: 0,
    explanation: 'Standard headers like "Experience" are commonly recognized by ATS and human reviewers.',
  },
  {
    id: 25,
    category: 'atsFormatting',
    difficulty: 'beginner',
    question: 'What is a formatting practice that helps both ATS and humans read your resume?',
    options: [
      'Use standard fonts and clear bullet points.',
      'Rely on complex multi-column layouts with floating elements.',
      'Embed text inside decorative shapes.',
      'Use extremely small font sizes to fit more text.',
    ],
    correctOptionIndex: 0,
    explanation: 'Standard fonts and bullets provide consistent structure that is easy to parse and read.',
  },
  {
    id: 26,
    category: 'atsFormatting',
    difficulty: 'intermediate',
    question: 'How can inconsistent date formats affect resume parsing?',
    options: [
      'They can confuse parsing tools and make timelines unclear.',
      'Date format has no effect on parsing.',
      'Inconsistent dates improve readability for ATS.',
      'They make the resume load faster.',
    ],
    correctOptionIndex: 0,
    explanation: 'Consistent date formats help both parsing tools and readers understand employment chronology.',
  },
  {
    id: 27,
    category: 'atsFormatting',
    difficulty: 'intermediate',
    question: 'Why should you avoid using tables for layout on a resume?',
    options: [
      'Tables used for visual layout can be misread by ATS and reorder content unexpectedly.',
      'Tables always improve ATS matching.',
      'Tables reduce file size which is preferred by ATS.',
      'Tables automatically convert to headings.',
    ],
    correctOptionIndex: 0,
    explanation: 'While tables can look neat visually, they often break the logical reading order for parsing systems.',
  },
  {
    id: 28,
    category: 'atsFormatting',
    difficulty: 'intermediate',
    question: 'What should you include in the filename when submitting a resume to make it clear to recruiters?',
    options: [
      'Your full name and the word "resume" (e.g., Firstname_Lastname_Resume.pdf).',
      'A generic name like "resume_final2.pdf" only.',
      'A file name with non-ASCII characters only.',
      'No file name, only paste content in the body.',
    ],
    correctOptionIndex: 0,
    explanation: 'A clear filename with your name helps recruiters and systems identify your document quickly.',
  },
  {
    id: 29,
    category: 'atsFormatting',
    difficulty: 'intermediate',
    question: 'Which resume element is most likely to be ignored by some ATS systems?',
    options: [
      'Text contained inside headers, footers, or images.',
      'Plain text in the main body.',
      'Standard section headers.',
      'Simple bullet points.',
    ],
    correctOptionIndex: 0,
    explanation: 'Some systems do not parse headers/footers or image text, so important details should be in the main content flow.',
  },
  {
    id: 30,
    category: 'atsFormatting',
    difficulty: 'advanced',
    question: 'How should you include keywords to improve ATS matching without keyword stuffing?',
    options: [
      'Integrate keywords naturally into accomplishment statements and skills sections.',
      'Repeat the same keyword in every sentence unnaturally.',
      'Hide keywords using white text on white background.',
      'Place keywords solely in an appendix.',
    ],
    correctOptionIndex: 0,
    explanation: 'Natural integration of keywords shows real experience and avoids penalties from automated checks.',
  },
  {
    id: 31,
    category: 'atsFormatting',
    difficulty: 'advanced',
    question: 'What is a reliable way to verify how an ATS will read your resume?',
    options: [
      'Use an ATS preview or parsing tool to inspect extracted text and structure.',
      'Convert the resume to an image and visually inspect it only.',
      'Send it to random websites without checking output.',
      'Rely entirely on formatting in a word processor preview.',
    ],
    correctOptionIndex: 0,
    explanation: 'ATS preview tools show how systems extract information and reveal potential parsing issues.',
  },
  {
    id: 32,
    category: 'atsFormatting',
    difficulty: 'advanced',
    question: 'When multiple roles exist under one employer, what layout helps both humans and ATS?',
    options: [
      'List the company once and include separate entries for each title with dates and responsibilities.',
      'Combine all roles into a single undifferentiated paragraph.',
      'Only list the most recent role and omit others.',
      'Use images to separate roles visually.',
    ],
    correctOptionIndex: 0,
    explanation: 'Separating titles with dates clarifies progression and preserves parseable structure for systems.',
  },
  {
    id: 33,
    category: 'atsFormatting',
    difficulty: 'advanced',
    question: 'What is the impact of including too many fonts and styles on a resume submitted to an ATS?',
    options: [
      'Varied fonts and styles can break rendering and make parsing less reliable.',
      'Multiple fonts always improve ATS detection of skills.',
      'Different fonts reduce file compatibility positively.',
      'ATS ignores font choices entirely without consequence.',
    ],
    correctOptionIndex: 0,
    explanation: 'Simple, standard fonts maintain compatibility and reduce parsing errors across systems.',
  },
  {
    id: 34,
    category: 'atsFormatting',
    difficulty: 'intermediate',
    question: 'Which contact information is most important to prioritize for ATS and recruiters?',
    options: [
      'A professional email and a reachable phone number.',
      'Your home mailing address only.',
      'A decorative contact badge image.',
      'Old contact details from college.',
    ],
    correctOptionIndex: 0,
    explanation: 'Email and phone are essential and should be current and professional for recruiter contact.',
  },
  {
    id: 35,
    category: 'atsFormatting',
    difficulty: 'advanced',
    question: 'How should you format a technical skills list to aid automated parsing?',
    options: [
      'Use comma-separated skill groups under a clear "Skills" heading.',
      'Embed skills inside an image of a chart.',
      'Scatter skills throughout paragraphs without a heading.',
      'List only proprietary abbreviations without explanation.',
    ],
    correctOptionIndex: 0,
    explanation: 'A clear "Skills" section with comma-separated items is easy for ATS to recognize and for humans to scan.',
  },

  // projectsSkills (43-63)
  {
    id: 43,
    category: 'projectsSkills',
    difficulty: 'beginner',
    question: 'How should you describe a college project on your resume?',
    options: [
      'State the project goal, your role, technologies used, and a measurable or demonstrable outcome.',
      'Mention only the project title without context.',
      'List the course name repeatedly.',
      'Describe unrelated hobbies instead of the project.',
    ],
    correctOptionIndex: 0,
    explanation: 'Even academic projects should show what you did, tools used, and the result or learning to highlight relevance.',
  },
  {
    id: 44,
    category: 'projectsSkills',
    difficulty: 'beginner',
    question: 'Which skill type belongs in a technical skills section?',
    options: [
      'Specific tools or languages like Python, SQL, or React.',
      'Favorite movies and books.',
      'A list of irrelevant personal interests.',
      'Only soft skills without examples.',
    ],
    correctOptionIndex: 0,
    explanation: 'Technical skills should list concrete tools and languages that relate to job requirements.',
  },
  {
    id: 45,
    category: 'projectsSkills',
    difficulty: 'beginner',
    question: 'What is a useful way to show your contribution on a team project?',
    options: [
      'Specify your role, key responsibilities, and one or two concrete achievements.',
      'Claim credit for the whole project without details.',
      'List the names of teammates only.',
      'State you contributed but provide no specifics.',
    ],
    correctOptionIndex: 0,
    explanation: 'Clarifying your role and measurable contributions helps employers evaluate your individual impact.',
  },
  {
    id: 46,
    category: 'projectsSkills',
    difficulty: 'beginner',
    question: 'If a project reduced load time by 40%, how should that appear on a resume?',
    options: [
      '"Reduced page load time by 40% by optimizing assets and caching."',
      '"Worked on performance improvements."',
      '"Improved UX."',
      '"Participated in speed initiatives."',
    ],
    correctOptionIndex: 0,
    explanation: 'Providing the percentage reduction with actions taken shows clear impact and methods used.',
  },
  {
    id: 47,
    category: 'projectsSkills',
    difficulty: 'intermediate',
    question: 'How should you present open-source contributions on your resume?',
    options: [
      'List the project, your contributions, links if allowed, and the impact or adoption.',
      'Only state you contributed without specifics.',
      'Hide contributions under a generic skills section.',
      'List only the programming language used.',
    ],
    correctOptionIndex: 0,
    explanation: 'Highlighting concrete contributions and impact helps demonstrate real-world usage and collaboration experience.',
  },
  {
    id: 48,
    category: 'projectsSkills',
    difficulty: 'intermediate',
    question: 'Which metric best communicates product impact for a feature you shipped?',
    options: [
      'Metrics like increased user engagement, retention, or revenue attributed to the feature.',
      'The number of meetings attended during development.',
      'A list of technologies without outcomes.',
      'Generic statements like "improved product" without data.',
    ],
    correctOptionIndex: 0,
    explanation: 'Attributing measurable change to the feature clarifies its significance to the business.',
  },
  {
    id: 49,
    category: 'projectsSkills',
    difficulty: 'intermediate',
    question: 'What is the best way to describe a technical skill you use frequently?',
    options: [
      'Show examples of how you applied it in projects and the results you achieved.',
      'List the skill without context or examples.',
      'Only include it in a long unrelated paragraph.',
      'Mention it in a footnote.',
    ],
    correctOptionIndex: 0,
    explanation: 'Concrete examples show depth of use and how the skill contributed to outcomes.',
  },
  {
    id: 50,
    category: 'projectsSkills',
    difficulty: 'advanced',
    question: 'How should you summarize a cross-functional project where you led engineers and designers?',
    options: [
      'Note the scope, team size, your decisions, and measurable outcomes such as time-to-market or revenue impact.',
      'Only list the team members’ names.',
      'Focus solely on the design without business context.',
      'Provide a vague statement about collaboration.',
    ],
    correctOptionIndex: 0,
    explanation: 'Context about scope and measurable results demonstrates leadership and product impact.',
  },
  {
    id: 51,
    category: 'projectsSkills',
    difficulty: 'advanced',
    question: 'When describing an architecture improvement, what elements are most helpful?',
    options: [
      'The problem addressed, the architectural change, and measurable system improvements.',
      'Only diagrams without explanation.',
      'Only mention the technology names.',
      'Exclude performance outcomes.',
    ],
    correctOptionIndex: 0,
    explanation: 'Explaining the problem, change, and measurable improvements communicates engineering judgment and impact.',
  },
  {
    id: 52,
    category: 'projectsSkills',
    difficulty: 'advanced',
    question: 'How can you show the transferability of technical skills to non-technical roles?',
    options: [
      'Highlight problem-solving, project management, and cross-team communication examples tied to outcomes.',
      'Only list programming languages without context.',
      'Focus on niche technical details irrelevant to the role.',
      'Omit soft skills entirely.',
    ],
    correctOptionIndex: 0,
    explanation: 'Framing technical skills around collaboration and outcomes shows applicability across roles.',
  },
  {
    id: 53,
    category: 'projectsSkills',
    difficulty: 'advanced',
    question: 'What is the best way to present a portfolio link on your resume?',
    options: [
      'Include a short, descriptive label and a clean URL or hyperlink under a Projects or Portfolio heading.',
      'Embed the entire portfolio as images in the resume.',
      'Provide a very long raw URL without context.',
      'Hide the link in small font at the footer where it is hard to find.',
    ],
    correctOptionIndex: 0,
    explanation: 'A clear label and accessible link allow reviewers to quickly explore your work.',
  },
  {
    id: 54,
    category: 'projectsSkills',
    difficulty: 'intermediate',
    question: 'How should you choose which skills to list at the top of your resume?',
    options: [
      'Prioritize the skills most relevant to the job description and supported by experience.',
      'List every skill you have regardless of relevance.',
      'Only include software you have never used.',
      'Include only soft skills without evidence.',
    ],
    correctOptionIndex: 0,
    explanation: 'Relevance and supporting experience make the skills list meaningful to the recruiter and ATS.',
  },
  {
    id: 55,
    category: 'projectsSkills',
    difficulty: 'intermediate',
    question: 'What should you avoid when describing the results of a project?',
    options: [
      'Vague language without metrics or clear outcomes.',
      'Specific metrics and before/after context.',
      'Concrete examples of your role.',
      'Clear timelines associated with results.',
    ],
    correctOptionIndex: 0,
    explanation: 'Vague descriptions make it hard to assess the actual impact of your work.',
  },

  // jobApplication (64-84)
  {
    id: 64,
    category: 'jobApplication',
    difficulty: 'beginner',
    question: 'Why should you tailor your resume for a specific job application?',
    options: [
      'To highlight the most relevant experience and keywords that match the role.',
      'To make the resume longer for all applications.',
      'To hide your true experience from recruiters.',
      'To reuse a single generic document for every job.',
    ],
    correctOptionIndex: 0,
    explanation: 'Tailoring increases perceived relevance and helps both ATS and recruiters identify a good fit.',
  },
  {
    id: 65,
    category: 'jobApplication',
    difficulty: 'beginner',
    question: 'What information is typically included in a concise cover letter?',
    options: [
      'A brief explanation of why you are interested, how your experience matches, and a call to action.',
      'A detailed list of every job duty from every role.',
      'Personal opinions on unrelated topics.',
      'Your entire academic transcript.',
    ],
    correctOptionIndex: 0,
    explanation: 'A good cover letter complements the resume by stating fit and motivation succinctly.',
  },
  {
    id: 66,
    category: 'jobApplication',
    difficulty: 'beginner',
    question: 'When submitting applications online, what should you check before sending?',
    options: [
      'That your resume file opens correctly, contact info is current, and any links work.',
      'That the file name contains private notes.',
      'Nothing—assume the system will fix all issues.',
      'That you removed all dates to avoid dating yourself.',
    ],
    correctOptionIndex: 0,
    explanation: 'Verifying file integrity and links reduces errors and ensures recruiters can access your materials.',
  },
  {
    id: 67,
    category: 'jobApplication',
    difficulty: 'beginner',
    question: 'What is an appropriate way to follow up after submitting an application if no timeline is given?',
    options: [
      'Wait one to two weeks and send a polite email expressing continued interest.',
      'Call every day until you hear back.',
      'Show up unannounced at the office.',
      'Publicly post complaints about the company online.',
    ],
    correctOptionIndex: 0,
    explanation: 'A polite follow-up after a reasonable wait shows interest without pressuring hiring teams.',
  },
  {
    id: 68,
    category: 'jobApplication',
    difficulty: 'intermediate',
    question: 'How should you tailor your resume when applying to a role that emphasizes teamwork?',
    options: [
      'Highlight collaborative projects, cross-functional work, and outcomes achieved with teams.',
      'Remove any mention of teamwork to focus on individual work only.',
      'Add fictional teams to appear collaborative.',
      'Only mention independent freelance work.',
    ],
    correctOptionIndex: 0,
    explanation: 'Demonstrating real team accomplishments aligns your experience with the role’s collaboration requirements.',
  },
  {
    id: 69,
    category: 'jobApplication',
    difficulty: 'intermediate',
    question: 'What is a good strategy for handling multiple job offers?',
    options: [
      'Compare roles, compensation, growth opportunities, and cultural fit before deciding.',
      'Accept the first offer immediately without consideration.',
      'Publicly announce acceptance before negotiating.',
      'Ignore offers and hope more appear.',
    ],
    correctOptionIndex: 0,
    explanation: 'Evaluating multiple factors helps you choose the best long-term fit, not just the highest immediate pay.',
  },
  {
    id: 70,
    category: 'jobApplication',
    difficulty: 'intermediate',
    question: 'When should you disclose salary expectations in the application process?',
    options: [
      'Share expectations when asked or during later-stage discussions; research market ranges first.',
      'Always include salary demands in the first resume you send.',
      'Never discuss salary until after one year of employment.',
      'Publicly list salary requirements on social media before applying.',
    ],
    correctOptionIndex: 0,
    explanation: 'Discuss salary at the appropriate stage with market knowledge to enable fair negotiation.',
  },
  {
    id: 71,
    category: 'jobApplication',
    difficulty: 'advanced',
    question: 'How should you prepare for behavioral interview questions that ask about past challenges?',
    options: [
      'Use the STAR method: Situation, Task, Action, Result, and focus on clear measurable outcomes.',
      'Recite unrelated technical facts.',
      'Avoid giving examples and speak hypothetically.',
      'Answer with one-word responses.',
    ],
    correctOptionIndex: 0,
    explanation: 'The STAR method gives structure to behavioral answers and highlights your contributions and impact.',
  },
  {
    id: 72,
    category: 'jobApplication',
    difficulty: 'advanced',
    question: 'What is an effective way to demonstrate cultural fit during the hiring process?',
    options: [
      'Research the company values and give examples of how your behavior aligns with them.',
      'Ignore the company culture and focus only on technical skills.',
      'Criticize the company’s leadership during interviews.',
      'Make up stories about previous employment to impress.',
    ],
    correctOptionIndex: 0,
    explanation: 'Concrete examples that align with company values show you understand and can contribute to the culture.',
  },
  {
    id: 73,
    category: 'jobApplication',
    difficulty: 'advanced',
    question: 'When negotiating an offer, what besides base salary should you consider?',
    options: [
      'Benefits, equity, vacation, flexible work arrangements, and professional development support.',
      'Only the company logo design.',
      'Irrelevant perks like office snacks only.',
      'Ignore all other terms and accept whatever is given.',
    ],
    correctOptionIndex: 0,
    explanation: 'Total compensation and work conditions affect long-term satisfaction and should be negotiated alongside salary.',
  },
  {
    id: 74,
    category: 'jobApplication',
    difficulty: 'intermediate',
    question: 'How should you handle a request to provide work samples that contain proprietary client data?',
    options: [
      'Offer redacted examples, summaries of the work, or recreated sample projects that demonstrate the skill.',
      'Provide the original proprietary files without permission.',
      'Refuse and say you have no relevant work.',
      'Give unrelated personal data instead.',
    ],
    correctOptionIndex: 0,
    explanation: 'Redacted or recreated examples convey ability while respecting confidentiality.',
  },
  {
    id: 75,
    category: 'jobApplication',
    difficulty: 'intermediate',
    question: 'What is the best practice for online professional profiles (e.g., LinkedIn) when job searching?',
    options: [
      'Keep them current, consistent with your resume, and highlight notable achievements with clear summaries.',
      'Leave them blank to avoid visibility.',
      'List every job duty without focus.',
      'Use unprofessional photos and language to stand out.',
    ],
    correctOptionIndex: 0,
    explanation: 'A current and consistent online profile supports your resume and helps recruiters find you.',
  },
  {
    id: 76,
    category: 'jobApplication',
    difficulty: 'advanced',
    question: 'When receiving feedback after an interview, what is the constructive way to respond?',
    options: [
      'Thank the interviewer, request clarification where helpful, and apply learnings to future interviews.',
      'Ignore the feedback entirely and react defensively publicly.',
      'Demand to be hired immediately.',
      'Provide unrelated criticism back to the interviewer.',
    ],
    correctOptionIndex: 0,
    explanation: 'Graciously receiving feedback and learning from it improves future performance and relationships with recruiters.',
  },

  // situationalScenarios (85-105)
  {
    id: 85,
    category: 'situationalScenarios',
    difficulty: 'beginner',
    question: 'If a job requires teamwork, which resume phrase best demonstrates that ability?',
    options: [
      'Collaborated with cross-functional teams to deliver features on time.',
      'Worked alone on all tasks without collaboration.',
      'Avoided meetings and independent work only.',
      'Preferred to work without communicating with others.',
    ],
    correctOptionIndex: 0,
    explanation: 'Collaborative language with outcomes demonstrates your ability to work effectively with others.',
  },
  {
    id: 86,
    category: 'situationalScenarios',
    difficulty: 'beginner',
    question: 'Which bullet best shows leadership on a resume?',
    options: [
      'Led a team to launch a feature that increased customer retention by 12%.',
      'Attended weekly team meetings regularly.',
      'Was present in team photos.',
      'Listed managerial responsibilities without results.',
    ],
    correctOptionIndex: 0,
    explanation: 'Specific leadership with measured outcomes clearly illustrates effective leadership.',
  },
  {
    id: 87,
    category: 'situationalScenarios',
    difficulty: 'beginner',
    question: 'How should you describe resolving a conflict on a team in an interview or resume?',
    options: [
      'Outline the situation, the actions you took to mediate, and the positive result.',
      'Avoid mentioning the conflict entirely.',
      'Blame others without context.',
      'Provide only an opinion without actions taken.',
    ],
    correctOptionIndex: 0,
    explanation: 'A concise description of actions and outcomes shows conflict resolution skills and maturity.',
  },
  {
    id: 88,
    category: 'situationalScenarios',
    difficulty: 'beginner',
    question: 'How should you highlight adaptability on a resume?',
    options: [
      'Describe an instance where you learned a new tool quickly and delivered results.',
      'State you are adaptable without examples.',
      'List only ways you resisted change.',
      'Omit adaptable experiences to avoid attention.',
    ],
    correctOptionIndex: 0,
    explanation: 'Concrete examples of rapid learning and results provide credible evidence of adaptability.',
  },
  {
    id: 89,
    category: 'situationalScenarios',
    difficulty: 'intermediate',
    question: 'How should you present a failure on your resume or interview to show growth?',
    options: [
      'Briefly explain the situation, what you learned, and how you changed your approach.',
      'Hide the failure and deny it happened.',
      'Blame external factors without reflection.',
      'Provide no follow-up about lessons learned.',
    ],
    correctOptionIndex: 0,
    explanation: 'Framing failures with lessons learned demonstrates resilience and continuous improvement.',
  },
  {
    id: 90,
    category: 'situationalScenarios',
    difficulty: 'intermediate',
    question: 'Which example best demonstrates initiative on a resume?',
    options: [
      'Proposed and implemented a process change that reduced onboarding time by 25%.',
      'Waited for assignments and followed instructions only.',
      'Reported problems but took no action.',
      'Avoided suggesting improvements to prevent conflict.',
    ],
    correctOptionIndex: 0,
    explanation: 'Initiative is shown by proposing and executing improvements that have measurable benefits.',
  },
  {
    id: 91,
    category: 'situationalScenarios',
    difficulty: 'intermediate',
    question: 'What is an effective way to communicate stakeholder management experience?',
    options: [
      'Describe how you identified stakeholders, aligned expectations, and delivered results.',
      'List stakeholders’ names without context.',
      'Say you worked with stakeholders but provide no examples.',
      'Avoid discussing stakeholder interactions entirely.',
    ],
    correctOptionIndex: 0,
    explanation: 'Detailing alignment and delivery shows your ability to manage stakeholder needs practically.',
  },
  {
    id: 92,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'How should you summarize a cross-functional initiative that required compromise and negotiation?',
    options: [
      'Explain the business goal, trade-offs negotiated, and the measurable outcome achieved.',
      'Only list the departments involved without outcomes.',
      'Describe the initiative with no mention of compromises.',
      'Claim the initiative failed without context.',
    ],
    correctOptionIndex: 0,
    explanation: 'Highlighting negotiations and outcomes shows your ability to lead complex collaborative work.',
  },
  {
    id: 93,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'Which framing best demonstrates strategic decision-making on a resume?',
    options: [
      'Describe the strategic problem, options considered, your decision, and the business impact.',
      'List tactical tasks completed without linking to strategy.',
      'Only mention high-level goals without actions.',
      'Include unrelated operational details.',
    ],
    correctOptionIndex: 0,
    explanation: 'Linking decisions to business impact demonstrates strategic thinking and measurable results.',
  },
  {
    id: 94,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'How can you show that you improved a process on the job?',
    options: [
      'State the baseline, the change you implemented, and the quantified improvement.',
      'Say "improved process" without numbers.',
      'Only describe the team meetings you held.',
      'List process steps without results.',
    ],
    correctOptionIndex: 0,
    explanation: 'Providing before-and-after metrics shows the effectiveness of your process improvement.',
  },
  {
    id: 95,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'What is the best way to demonstrate ethical decision-making in a professional example?',
    options: [
      'Describe the dilemma, the principled actions you took, and the outcome that respected stakeholders.',
      'Avoid mentioning ethics to prevent controversy.',
      'Just state you always act ethically without an example.',
      'Blame others for ethical failures.',
    ],
    correctOptionIndex: 0,
    explanation: 'Concrete examples of principled action and outcomes show integrity and judgment.',
  },
  {
    id: 96,
    category: 'situationalScenarios',
    difficulty: 'intermediate',
    question: 'How should you present a time when you had to learn a new tool quickly?',
    options: [
      'Explain the learning steps you took and the results you delivered using the tool.',
      'State you learned it without providing results.',
      'Mention the tool name and stop there.',
      'Say you avoided using the tool entirely.',
    ],
    correctOptionIndex: 0,
    explanation: 'Describing how you learned and applied a tool demonstrates capacity to adapt and produce outcomes.',
  },
  {
    id: 97,
    category: 'situationalScenarios',
    difficulty: 'intermediate',
    question: 'What is a strong example of customer-focused thinking to include on a resume?',
    options: [
      'Implemented a feature that improved customer satisfaction scores by X% through direct research.',
      'Worked on internal tooling with no customer insight.',
      'Designed features without user feedback.',
      'Only documented internal processes.',
    ],
    correctOptionIndex: 0,
    explanation: 'Linking actions to customer outcomes demonstrates user-centered decision-making.',
  },
  {
    id: 98,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'How should you present a complex negotiation where you achieved a win-win outcome?',
    options: [
      'Describe the objectives of each party, the compromise reached, and the measurable benefit to both sides.',
      'Claim victory without acknowledging trade-offs.',
      'Only describe your demands.',
      'Omit any mention of negotiation details.',
    ],
    correctOptionIndex: 0,
    explanation: 'Explaining trade-offs and benefits shows your ability to negotiate strategically and create value.',
  },
  {
    id: 99,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'What details should you include when describing a major product pivot you led?',
    options: [
      'Context for the pivot, reasoning, stakeholder alignment actions, and measurable post-pivot results.',
      'Only the announcement date without strategic details.',
      'List the names of team members but no outcomes.',
      'Provide a vague statement that a pivot occurred.',
    ],
    correctOptionIndex: 0,
    explanation: 'Context, decisions, and outcomes demonstrate leadership in navigating major strategic changes.',
  },
  {
    id: 100,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'Which example best shows you can scale a process across teams?',
    options: [
      'Describe the pilot, the standardization steps, and the metrics showing successful adoption across teams.',
      'State you like scaling processes without examples.',
      'List the pilot activities only without results.',
      'Say you prefer to keep processes small and manual.',
    ],
    correctOptionIndex: 0,
    explanation: 'Showing pilot to rollout metrics demonstrates ability to scale effective practices across organizations.',
  },
  {
    id: 101,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'How can you represent influence without formal authority on a resume?',
    options: [
      'Show instances where you persuaded stakeholders, built consensus, and achieved outcomes.',
      'Only list your formal titles.',
      'Avoid discussing influence and power dynamics.',
      'Claim authority you did not have.',
    ],
    correctOptionIndex: 0,
    explanation: 'Describing consensus-building and outcomes shows real influence beyond formal reporting lines.',
  },
  {
    id: 102,
    category: 'situationalScenarios',
    difficulty: 'intermediate',
    question: 'Which action demonstrates effective time management on a resume?',
    options: [
      'Prioritized tasks, set milestones, and met deadlines while maintaining quality.',
      'Ignored deadlines and worked at leisure.',
      'Only described meetings attended without output.',
      'Reported random work hours without outcomes.',
    ],
    correctOptionIndex: 0,
    explanation: 'Concrete time management practices tied to outcomes show reliability and execution ability.',
  },
  {
    id: 103,
    category: 'situationalScenarios',
    difficulty: 'intermediate',
    question: 'What is an appropriate way to present mentoring experience?',
    options: [
      'Describe the number of mentees, skills developed, and measurable improvements where possible.',
      'Say you mentored without providing any details.',
      'List only the mentees’ names.',
      'Mention mentoring as a hobby unrelated to work.',
    ],
    correctOptionIndex: 0,
    explanation: 'Quantifying mentoring outcomes demonstrates the scope and effectiveness of your coaching.',
  },
  {
    id: 104,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'How should you document a cross-border collaboration to show global competency?',
    options: [
      'Note the regions involved, coordination mechanisms, and business results achieved across locations.',
      'Mention only local tasks without context.',
      'List time zones without describing coordination.',
      'Omit any mention of global factors.',
    ],
    correctOptionIndex: 0,
    explanation: 'Detailing coordination and outcomes demonstrates capability to work effectively across geographies.',
  },
  {
    id: 105,
    category: 'situationalScenarios',
    difficulty: 'advanced',
    question: 'What is the best way to show you led a turnaround for a failing project?',
    options: [
      'Explain the initial challenges, the corrective actions you led, and the measurable recovery results.',
      'Claim the project improved without describing actions.',
      'Hide the failure and only present later successes without linkage.',
      'Attribute the turnaround entirely to others without describing your role.',
    ],
    correctOptionIndex: 0,
    explanation: 'Showing the problem, the interventions, and measurable recovery demonstrates effective leadership in crises.',
  },
]

export function getQuizQuestions(category: QuizCategory, difficulty: QuizDifficulty) {
  const questionLimit = difficulty === 'beginner' ? 4 : difficulty === 'intermediate' ? 7 : 10

  const pool =
    category === 'mixed'
      ? RESUME_QUIZ_QUESTIONS.filter((q) => q.difficulty === difficulty && q.category !== 'mixed')
      : RESUME_QUIZ_QUESTIONS.filter((q) => q.category === category && q.difficulty === difficulty)

  // Shuffle and return the requested number
  const shuffled = [...pool].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, questionLimit)
}

